Commerceshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [

    # Homepage
    path("", views.index, name="index"),
    path("products/", views.product_list_view, name="product-list"),
    path("products/<str:pid>", views.product_detail_view, name="product-detail"),

    # Categories
    path("categories/",views.category_list_view, name="category-list"),
    path("categories/<str:cid>", views.product_list_view_with_category, name="product-list-with-category"),

    # Vendor
    path("vendors/", views.vendor_list_view, name="vendor-list"),
    path("vendors/<str:vid>", views.vendor_detail_view, name="vendor-detail"),

    # Tag
    path("products/tag/<slug:tag_slug>", views.tag_list, name="product-list-with-tag"),

    # Add Review
    path("ajax-add-review/<str:pid>", views.ajax_add_review, name="ajax-add-review"),

    # Search
    path("search/", views.search_view, name="search"),

    # Filter
    path("filtered-products/", views.filter_product, name="filter"),

    # Add product to cart
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),

    # Cart page
    path("cart/", views.cart_view, name="cart"),

    # Remove product from cart
    path("remove-from-cart/", views.remove_from_cart, name="remove-from-cart"),

    # Update product from cart
    path("update-cart/", views.update_cart, name="update-cart"),

    # Checkout
    path("save-checkout-info/", views.save_checkout_info, name="save-checkout-info"),

    path("checkout/<str:oid>/", views.checkout, name="checkout"),

    path("api/create_checkout_session/<str:oid>/", views.create_checkout_session, name="create-checkout-session"),

    # Paypal payment
    path("paypal/", include("paypal.standard.ipn.urls")),
    
    # Payment successful
    path("payment-completed/<str:oid>", views.payment_completed_view, name="payment-completed"),

    # Payment failed
    path("payment-failed/", views.payment_failed_view, name="payment-failed"),

    # Dashboard URL
    path("dashboard/", views.customer_dashboard, name="dashboard"),

    # Order detail
    path("dashboard/orders/<int:id>", views.order_detail, name="order-detail"),

    # Make address default
    path("default-address/", views.make_address_default, name="make-address-default"),

    # Wishlist page
    path("wishlist/", views.wishlist_view, name="wishlist"),

    # Add product to wishlist
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),

    # Remove product from wishlist
    path("remove-from-wishlist/", views.remove_from_withlist, name="remove-from-withlist"),

    # Contact page
    path("contact/", views.contact, name="contact"),

    # Contact with ajax
    path("contact-ajax/", views.contact_ajax, name="contact-ajax"),
]

useradmin/urls.py
from django.urls import path
from . import views

app_name = "useradmin"

urlpatterns = [
    # Dashboard
    path('dashboard/', views.dashboard, name='dashboard'),

    # Product CRUD
    path("products/", views.products, name="products"),

    path('add-product/', views.add_product, name="add-product"),

    path("edit-product/<str:pid>", views.edit_product, name="edit-product"),

    path("delete-product/<str:pid>", views.delete_product, name="delete-product"),

    # Orders

    path("orders/", views.orders, name="orders"),
    
    path("order-detail/<str:oid>", views.order_detail, name="order-detail"),

    path("update-order-status/<str:oid>", views.update_order_status, name="update-order-status"),

    # Shop page
    path("shop-page/", views.shop_page, name="shop-page"),

    # Review
    path("reviews/", views.reviews, name="reviews"),

    # Settings
    path("settings/", views.settings, name="settings"),

    # Change password
    path("change-password/", views.change_password, name="change-password"),
]

userauths/urls.py
from django.urls import path
from . import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/",views.register_view, name="sign-up"),
    path("sign-in/",views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),
    path("profile/update/", views.profile_update, name="profile-update"),
]

useradmin/models.py
from django.db import models

# Create your models here.

useradmin/forms.py
from core.models import Product
from django import forms 

class AddProductForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Enter product title", "class": "form-control"}))
    description = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Product Description", "class":"form-control"}))
    price = forms.DecimalField(widget=forms.NumberInput(attrs={'placeholder': "Sale Price", "class":"form-control"}))
    old_price = forms.DecimalField(widget=forms.NumberInput(attrs={'placeholder': "Old Price", "class":"form-control"}))
    type = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Type of product e.g organic cream", "class":"form-control"}))
    stock = forms.CharField(widget=forms.NumberInput(attrs={'placeholder': "How many are in stock?", "class":"form-control"}))
    life = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "How long would this product live?", "class":"form-control"}))
    mfg = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'placeholder': "e.g: 24/01/21", "class":"form-control"}))
    tags = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Tags", "class":"form-control"}))
    image = forms.ImageField(widget=forms.FileInput(attrs={"class":"form-control"}))

    class Meta:
        model = Product
        fields = [
            'title',
            'image',
            'description',
            'price',
            'old_price',
            'specifications',
            'type',
            'stock',
            'life',
            'mfg',
            'tags',
            'digital',
            'category',
        ]

useradmin/views.py
from django.shortcuts import render, redirect
from core.models import CartOrder, Product, Category, CartOrderItem, ProductReview
from userauths.models import Profile
from django.contrib import messages
from django.contrib.auth.hashers import check_password
from django.db.models import Sum
from django.shortcuts import get_object_or_404
from userauths.models import User
from useradmin.forms import AddProductForm
from useradmin.decorators import admin_required

import datetime

# Create your views here.

@admin_required
def dashboard(request):
    revenue = CartOrder.objects.aggregate(price=Sum("price"))
    orders = CartOrder.objects.all().order_by("-order_date")
    order_count = orders.count()
    products = Product.objects.all()
    categories = Category.objects.all()
    customers = User.objects.all().order_by("-id")
    
    this_month = datetime.datetime.now().month 

    monthly_revenue = (CartOrder.objects.filter(order_date__month=this_month)).aggregate(price=Sum("price"))

    context = {
        "orders": orders,
        "order_count": order_count,
        "revenue": revenue["price"],
        "products": products,
        "categories": categories,
        "customers": customers,
        "monthly_revenue": monthly_revenue,
    }

    return render(request, "useradmin/dashboard.html", context)

@admin_required
def products(request):
    products =  Product.objects.all().order_by("-date")
    categories = Category.objects.all()

    context = {
        "products": products,
        "categories": categories,
    }
    
    return render(request, "useradmin/products.html", context)

@admin_required
def add_product(request):
    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            new_form  = form.save(commit=False)
            new_form.user =  request.user
            new_form.save()
            # Save many to many fields
            form.save_m2m()
            return redirect("useradmin:dashboard")
        else:
            return render(request, "useradmin/add-product.html", {"form": form})
    else:
        form = AddProductForm()
        return render(request, "useradmin/add-product.html", {"form": form})


@admin_required
def edit_product(request, pid):
    product = Product.objects.get(pid=pid)
    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            new_form  = form.save(commit=False)
            new_form.user =  request.user
            new_form.save()
            # Save many to many fields
            form.save_m2m()
            return redirect("useradmin:edit-product", product.pid)
        else:
            return render(request, "useradmin/add-product.html", {"form": form, "product": product})
    else:
        form = AddProductForm(instance=product)
        return render(request, "useradmin/edit-product.html", {"form": form, "product": product})

@admin_required
def delete_product(request, pid):
    product = Product.objects.get(pid=pid)
    product.delete()
    return redirect("useradmin:products")  


@admin_required
def orders(request):
    orders = CartOrder.objects.all().order_by("-order_date")
    context = {
        "orders": orders
    }
    
    return render(request, "useradmin/orders.html", context)

@admin_required
def order_detail(request, oid):
    order = get_object_or_404(CartOrder, oid=oid)
    items = order.items.all()

    context = {
        "order": order,
        "items": items,
    }
    return render(request, "useradmin/order-detail.html", context)


@admin_required
def update_order_status(request, oid):
    order = CartOrder.objects.get(oid=oid)
    if request.method == "POST":
        status = request.POST.get("status")
        order.product_status = status
        order.save()
        messages.success(request, f"Order status changed to {status}")
    return redirect("useradmin:order-detail", order.oid)

@admin_required
def shop_page(request):
    products = Product.objects.all()
    revenue = CartOrder.objects.aggregate(price=Sum("price"))
    total_sales = CartOrderItem.objects.aggregate(quantity=Sum("quantity"))

    context = {
        "products": products,
        "revenue": revenue,
        "total_sales": total_sales,
    }
    return render(request, "useradmin/shop-page.html", context)


@admin_required
def reviews(request):
    reviews = ProductReview.objects.all().order_by("-date")
    context = {
        "reviews": reviews,
    }

    return render(request, "useradmin/reviews.html", context)

@admin_required
def settings(request):
    profile = Profile.objects.get(user=request.user)

    if request.method == "POST":
        image = request.FILES.get("image")
        full_name = request.POST.get("full_name")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        address = request.POST.get("address")
        country = request.POST.get("country")

        if image != None:
            profile.image = image
        profile.full_name = full_name
        profile.email = email
        profile.phone = phone
        profile.address = address
        profile.country = country
        profile.save()
        messages.success(request, "Profile updated successfully")
        return redirect("useradmin:settings")
    context = {
        "profile": profile,
    }
    return render(request, "useradmin/settings.html", context)

@admin_required
def change_password(request):
    user = request.user
    if request.method == "POST":
        old_password = request.POST.get("old_password")
        new_password = request.POST.get("new_password")
        confirm_password = request.POST.get("confirm_password")

        if check_password(old_password, user.password):
            if confirm_password != new_password:
                messages.warning(request, "Passwords do not match")
            else:
                user.set_password(new_password)
                user.save()
                messages.success(request, "Passwords changed successfully")
                return redirect("useradmin:change-password")
        else:
            messages.warning(request, "Old password is incorrect")
            return redirect("useradmin:change-password")
    return render(request, "useradmin/change-password.html")

templates/useradmin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>E-commerce Dashboard</title>
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:title" content="" />
        <meta property="og:type" content="" />
        <meta property="og:url" content="" />
        <meta property="og:image" content="" />
        <!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="assets2/imgs/theme/favicon.svg" />
        <!-- Template CSS -->
        <link href="{% static 'assets2/css/main.css' %}" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />

    </head>

    <body>
        <div class="screen-overlay"></div>
        <aside class="navbar-aside" id="offcanvas_aside">
            <div class="aside-top">
                <a href="index.html" class="brand-wrap">
                    <img src="{% static 'assets2/imgs/theme/logo.svg' %}" class="logo" alt="E-commerce Dashboard" />
                </a>
                <div>
                    <button class="btn btn-icon btn-aside-minimize"><i class="text-muted material-icons md-menu_open"></i></button>
                </div>
            </div>
            <nav>
                <ul class="menu-aside">
                    <li class="menu-item {% if '/useradmin/dashboard' in request.path %}active{% endif %}">
                        <a class="menu-link" href="{% url 'useradmin:dashboard' %}">
                            <i class="icon material-icons md-home"></i>
                            <span class="text">Dashboard</span>
                        </a>
                    </li>
                    <li class="menu-item {% if '/useradmin/products' in request.path %}active{% endif %}">
                        <a class="menu-link" href="{% url 'useradmin:products' %}">
                            <i class="icon material-icons md-shopping_bag"></i>

                            <span class="text">Products</span>
                        </a>
                    </li>
                    <li class="menu-item {% if '/useradmin/orders' in request.path %}active{% endif %}">
                        <a class="menu-link" href="{% url 'useradmin:orders' %}">
                            <i class="icon material-icons md-shopping_cart"></i>
                            <span class="text">Orders</span>
                        </a>
                    </li>
                    <li class="menu-item {% if '/useradmin/shop-page' in request.path %}active{% endif %}">
                        <a class="menu-link " href="{% url 'useradmin:shop-page' %}">
                            <i class="icon material-icons md-store"></i>
                            <span class="text">Shop Page</span>
                        </a>
                    </li>
                    <li class="menu-item {% if 'useradmin/add-product' in request.path %}active{% endif %}">
                        <a class="menu-link" href="{% url 'useradmin:add-product' %}">
                            <i class="icon material-icons md-add_box"></i>
                            <span class="text">Add product</span>
                        </a>
                    </li>
                    <li class="menu-item ">
                        <a class="menu-link" href="page-transactions-1.html">
                            <i class="icon material-icons md-monetization_on"></i>
                            <span class="text">Transactions History</span>
                        </a>
                    </li>

                    <li class="menu-item {% if '/useradmin/reviews' in request.path %}active {% endif %}">
                        <a class="menu-link" href="{% url 'useradmin:reviews' %}">
                            <i class="icon material-icons md-comment"></i>
                            <span class="text">Reviews</span>
                        </a>
                    </li>
                    
                    
                </ul>
                <hr />
                <ul class="menu-aside">
                    <li class="menu-item {% if 'useradmin/settings' in request.path %}active{% endif %}">
                        <a class="menu-link" href="{% url 'useradmin:settings' %}">
                            <i class="icon material-icons md-settings"></i>
                            <span class="text">Settings</span>
                        </a>
                        <div class="submenu">
                            <a href="page-settings-1.html">Setting sample 1</a>
                            <a href="page-settings-2.html">Setting sample 2</a>
                        </div>
                    </li>
                    <li class="menu-item {% if 'useradmin/change-password' in request.path %}active{% endif %}">
                        <a class="menu-link" href="{% url 'useradmin:change-password' %}">
                            <i class="icon material-icons md-lock"></i>
                            <span class="text"> Change Password </span>
                        </a>
                    </li>

                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'userauths:sign-out' %}">
                            <i class="icon material-icons md-arrow_forward"></i>
                            <span class="text">Logout</span>
                        </a>
                    </li>
                </ul>
                <br />
                <br />
            </nav>
        </aside>
        <main class="main-wrap">
            <header class="main-header navbar">
                <div class="col-search">
                    <form class="searchform">
                        <div class="input-group">
                            <input list="search_terms" type="text" class="form-control" placeholder="Search term" />
                            <button class="btn btn-light bg" type="button"><i class="material-icons md-search"></i></button>
                        </div>
                        <datalist id="search_terms">
                            <option value="Products"></option>
                            <option value="New orders"></option>
                            <option value="Apple iphone"></option>
                            <option value="Ahmed Hassan"></option>
                        </datalist>
                    </form>
                </div>
                <div class="col-nav">
                    <button class="btn btn-icon btn-mobile me-auto" data-trigger="#offcanvas_aside"><i class="material-icons md-apps"></i></button>
                    <ul class="nav">
                        <li class="nav-item">
                            <a class="nav-link btn-icon" href="#">
                                <i class="material-icons md-notifications animation-shake"></i>
                                <span class="badge rounded-pill">3</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn-icon darkmode" href="#"> <i class="material-icons md-nights_stay"></i> </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="requestfullscreen nav-link btn-icon"><i class="material-icons md-cast"></i></a>
                        </li>
                        <li class="dropdown nav-item">
                            <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownLanguage" aria-expanded="false"><i class="material-icons md-public"></i></a>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownLanguage">
                                <a class="dropdown-item text-brand" href="#"><img src="{% static 'assets2/imgs/theme/flag-us.png' %}" alt="English" />English</a>
                                <a class="dropdown-item" href="#"><img src="{% static 'assets2/imgs/theme/flag-fr.png' %}" alt="Français" />Français</a>
                                <a class="dropdown-item" href="#"><img src="{% static 'assets2/imgs/theme/flag-jp.png' %}" alt="Français" />日本語</a>
                                <a class="dropdown-item" href="#"><img src="{% static 'assets2/imgs/theme/flag-cn.png' %}" alt="Français" />中国人</a>
                            </div>
                        </li>
                        <li class="dropdown nav-item">
                            <a class="dropdown-toggle" data-bs-toggle="dropdown" href="#" id="dropdownAccount" aria-expanded="false"> <img class="img-xs rounded-circle" src="{% static 'assets2/imgs/people/avatar-2.png' %}" alt="User" /></a>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownAccount">
                                <a class="dropdown-item" href="#"><i class="material-icons md-perm_identity"></i>Edit Profile</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-settings"></i>Account Settings</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-account_balance_wallet"></i>Wallet</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-receipt"></i>Billing</a>
                                <a class="dropdown-item" href="#"><i class="material-icons md-help_outline"></i>Help center</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item text-danger" href="#"><i class="material-icons md-exit_to_app"></i>Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
                
            </header>
            {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{message.tags}}">
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <script>
                    setTimeout (() => {
                        $(".alert").alert("close");
                    }, 3000)
                </script>

            {% block content %} 
            
            {% endblock content %}

            <!-- content-main end// -->
            <footer class="main-footer font-xs">
                <div class="row pb-30 pt-15">
                    <div class="col-sm-6">
                        <script>
                            document.write(new Date().getFullYear());
                        </script>
                        &copy; E-commerce - HTML Ecommerce Template .
                    </div>
                    <div class="col-sm-6">
                        <div class="text-sm-end">All rights reserved</div>
                    </div>
                </div>
            </footer>
        </main>
        <script src="{% static 'assets2/js/vendors/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/select2.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/perfect-scrollbar.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/jquery.fullscreen.min.js' %}"></script>
        <script src="{% static 'assets2/js/vendors/chart.js' %}"></script>
        <!-- Main Script -->
        <script src="{% static 'assets2/js/main.js?v=1.1' %}" type="text/javascript"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <!-- <script src="{% static 'assets2/js/custom-chart.js' %}" type="text/javascript"></script> -->
    </body>
</html>

templates/useradmin/change-password.html
{% extends 'useradmin/base.html' %}
{% load static %} 

{% block content %}
<section class="content-main">
    <div class="content-header">
        <h2 class="content-title">Change Password</h2>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row gx-5">
                <div class="col-lg-12">
                    <section class="content-body p-xl-4">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-8">
                                    <div class="row gx-3">
                                        <div class="col-12 mb-3">
                                            <label class="form-label">Old Password</label>
                                            <input class="form-control" name="old_password" value="" type="password" placeholder="***********" />
                                        </div>
                                        <div class="col-12 mb-3">
                                            <label class="form-label">New Password</label>
                                            <input class="form-control" name="new_password" value="" type="password" placeholder="***********" />
                                        </div>
                                        <div class="col-lg-12 mb-3">
                                            <label class="form-label">Confirm Password</label>
                                            <input class="form-control" name="confirm_password" value="" type="password" placeholder="***********" />
                                        </div>
                                    </div>
                                </div>
                                <aside class="col-lg-4">
                                    <figure class="text-lg-center">
                                        {% if request.user.profile.image %}
                                        <img class="img-lg mb-3 img-avatar" src="{{request.user.profile.image.url}}" alt="User Photo" />
                                        {% else %}
                                        <img class="img-lg mb-3 img-avatar" src="https://www.shutterstock.com/image-vector/vector-flat-illustration-grayscale-avatar-600nw-2281862025.jpg" alt="User Photo" />
                                        {% endif %}
                                    </figure>
                                </aside>
                            </div>
                            <br />
                            <button class="btn btn-primary" type="submit">Save New Password <i class="fas fa-check-circle mt-1 ms-2"></i></button>
                        </form>
                    </section>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/useradmin/products.html
{% extends 'useradmin/base.html' %}
{% load static %}

{% block content %}
<section class="content-main">
    <div class="content-header">
        <div>
            <h2 class="content-title card-title">Products List</h2>
            <p>Manage all your products from here</p>
        </div>
        <div>
            <a href="{% url 'useradmin:add-product' %}" class="btn btn-primary btn-sm rounded">Create Product</a>
        </div>
    </div>
    <div class="card mb-4">
        <header class="card-header">
            <div class="row align-items-center">
                <div class="col-md-2 col-6">
                    <select class="form-select">
                        <option selected>Status</option>
                        <option>Active</option>
                        <option>Disabled</option>
                        <option>Show all</option>
                    </select>
                </div>
            </div>
        </header>
        <div class="card-body">
            <article class="itemlist">
                {% for product in products %}
                <div class="row align-items-center">
                    <div class="col col-check flex-grow-0">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" />
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-4 col-8 flex-grow-1 col-name">
                        <a class="itemside" href="">
                            <div class="left">
                                <img src="{{product.image.url}}" style="width: 100px; height: 100px; object-fit: cover; border-radius: 15px" class="img-sm img-thumbnail" alt="Item" />
                            </div>
                            <div class="info">
                                <h6 class="mb-0">{{product.title}}</h6>
                            </div>
                        </a>
                    </div>
                    <div class="col-lg-2 col-sm-2 col-4 col-price"><span>${{product.price}}</span></div>
                    <div class="col-lg-2 col-sm-2 col-4 col-status">
                        <span class="badge alert-dark">{{product.status}}</span>
                    </div>
                    <div class="col-lg-1 col-sm-2 col-4 col-date">
                        <span>{{product.date|date:"d M, Y"}}</span>
                    </div>
                    <div class="col-lg-2 col-sm-2 col-4 col-action text-end">
                        <a href="{% url 'useradmin:edit-product' product.pid %}" class="btn btn-sm font-sm rounded btn-brand"> <i class="material-icons md-edit"></i> Edit </a>
                        <a href="{% url 'useradmin:delete-product' product.pid %}" class="btn btn-sm font-sm btn-light rounded"> <i class="material-icons md-delete_forever"></i> Delete </a>
                    </div>
                    <hr>
                </div>
                {% endfor %}
            </article>
        </div>
    </div>
    <div class="pagination-area mt-30 mb-50">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-start">
                <li class="page-item active"><a class="page-link" href="#">01</a></li>
                <li class="page-item"><a class="page-link" href="#">02</a></li>
                <li class="page-item"><a class="page-link" href="#">03</a></li>
                <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                <li class="page-item"><a class="page-link" href="#">16</a></li>
                <li class="page-item">
                    <a class="page-link" href="#"><i class="material-icons md-chevron_right"></i></a>
                </li>
            </ul>
        </nav>
    </div>
</section>
{% endblock %}