Commerceshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("useradmin/", include("useradmin.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from . import views

app_name = 'core'

urlpatterns = [

    # Homepage
    path("", views.index, name="index"),
    path("products/", views.product_list_view, name="product-list"),
    path("products/<str:pid>", views.product_detail_view, name="product-detail"),

    # Categories
    path("categories/",views.category_list_view, name="category-list"),
    path("categories/<str:cid>", views.product_list_view_with_category, name="product-list-with-category"),

    # Vendor
    path("vendors/", views.vendor_list_view, name="vendor-list"),
    path("vendors/<str:vid>", views.vendor_detail_view, name="vendor-detail"),

    # Tag
    path("products/tag/<slug:tag_slug>", views.tag_list, name="product-list-with-tag"),

    # Add Review
    path("ajax-add-review/<str:pid>", views.ajax_add_review, name="ajax-add-review"),

    # Search
    path("search/", views.search_view, name="search"),

    # Filter
    path("filtered-products/", views.filter_product, name="filter"),

    # Add product to cart
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),

    # Cart page
    path("cart/", views.cart_view, name="cart"),

    # Remove product from cart
    path("remove-from-cart/", views.remove_from_cart, name="remove-from-cart"),

    # Update product from cart
    path("update-cart/", views.update_cart, name="update-cart"),

    # Checkout
    path("save-checkout-info/", views.save_checkout_info, name="save-checkout-info"),

    path("checkout/<str:oid>/", views.checkout, name="checkout"),

    path("api/create_checkout_session/<str:oid>/", views.create_checkout_session, name="create-checkout-session"),

    # Paypal payment
    path("paypal/", include("paypal.standard.ipn.urls")),
    
    # Payment successful
    path("payment-completed/<str:oid>", views.payment_completed_view, name="payment-completed"),

    # Payment failed
    path("payment-failed/", views.payment_failed_view, name="payment-failed"),

    # Dashboard URL
    path("dashboard/", views.customer_dashboard, name="dashboard"),

    # Order detail
    path("dashboard/orders/<int:id>", views.order_detail, name="order-detail"),

    # Make address default
    path("default-address/", views.make_address_default, name="make-address-default"),

    # Wishlist page
    path("wishlist/", views.wishlist_view, name="wishlist"),

    # Add product to wishlist
    path("add-to-wishlist/", views.add_to_wishlist, name="add-to-wishlist"),

    # Remove product from wishlist
    path("remove-from-wishlist/", views.remove_from_withlist, name="remove-from-withlist"),

    # Contact page
    path("contact/", views.contact, name="contact"),

    # Contact with ajax
    path("contact-ajax/", views.contact_ajax, name="contact-ajax"),
]

core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Write your review about the product "}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from datetime import datetime
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse, Http404, JsonResponse
from django.db.models import Avg, Count
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from core.models import Coupon, Product, Category, Vendor, CartOrder, CartOrderItem, WishList, ProductImage, ProductReview, Address
from userauths.models import ContactUs, Profile
from taggit.models import Tag
from django.contrib.auth.decorators import login_required
from core.forms import ProductReviewForm
import math
import stripe

import calendar
from django.db.models.functions import ExtractMonth



# Create your views here.
def index(request):
    products = Product.objects.filter(featured=True, product_status="published")
    return render(request, 'core/index.html', {
        "products": products, 
    })
    

def product_list_view(request):
    products = Product.objects.filter(product_status="published").order_by("-id")
    return render(request, 'core/product-list.html', {
        "products": products, 
    })

def category_list_view(request):
    categories = Category.objects.all()
    return render(request, 'core/category-list.html', {"categories": categories})

def product_list_view_with_category(request, cid):
    try:
        category = Category.objects.get(cid=cid)
        products = Product.objects.filter(product_status="published", category=category)
        return render(request, "core/category-product-list.html", {
            "category": category,
            "products": products,
        })
    except Category.DoesNotExist:
        raise Http404("Category not found.")
        
def vendor_list_view(request):
    vendors = Vendor.objects.all()
    return render(request, "core/vendor-list.html", {"vendors": vendors})

def vendor_detail_view(request, vid):
    try:
        vendor = Vendor.objects.get(vid=vid)
        products = Product.objects.filter(vendor=vendor, product_status="published")
        return render(request, "core/vendor-detail.html", {
            "vendor": vendor,
            "products": products,
            })
    except Vendor.DoesNotExist:
        raise Http404("Vendor not found.")

# @login_required(login_url="userauths:sign-in")
def product_detail_view(request, pid):
    product = get_object_or_404(Product, pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid)
    
    # Get all reviews of the product
    reviews = product.reviews.all().order_by("-date")

    #Get average rating of the product
    average_rating = reviews.aggregate(rating=Avg('rating'))

    p_image = product.product_images.all()
    vendor = product.vendor

    # Product review form
    review_form = ProductReviewForm()

    is_authenticated = request.user.is_authenticated
    allow_to_add_review = True
    if is_authenticated:
        user_review_count = reviews.filter(user=request.user, product=product).count()
        if user_review_count > 0:
            allow_to_add_review = False
    return render(request, "core/product-detail.html", {
        "product": product,
        "vendor": vendor,
        "products": products,
        "p_image": p_image,
        "reviews": reviews,
        "average_rating": average_rating,
        "review_form": review_form,
        "is_logged_in": is_authenticated,
        "allow_to_add_review": allow_to_add_review,
    })

def tag_list(request, tag_slug=None):
    products = Product.filter(product_status="published").order_by("-id")
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])
    return render(request, "core/tag.html", {
        "products": products,
        "tag": tag,
    })

@login_required()
def ajax_add_review(request, pid):
    product = Product.objects.get(pid=pid)
    user = request.user

    review = ProductReview.objects.create(
        user=user,
        product=product,
        review=request.POST['review'],
        rating=request.POST['rating']
    )
    
    context = {
        'user': user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating'],
    }
    average_rating = product.reviews.all().aggregate(rating=Avg("rating"))

    return JsonResponse({
        'bool': True,
        'context': context,
        'average_rating': average_rating,
        'date': review.date.strftime('%d %B, %Y'),
    })

def search_view(request):
    query = request.GET["q"]

    products = Product.objects.filter(title__icontains=query).order_by("-date") 
    context = {
        "products": products,
        "query": query,
    }

    return render(request, "core/search.html", context)

def filter_product(request):
    categories = request.GET.getlist('category[]')
    vendors = request.GET.getlist('vendor[]')

    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(product_status="published").order_by("-id", "date")
    products = products.filter(price__gte=min_price).filter(price__lte=math.ceil(float(max_price)))

    if len(categories) > 0:
        products = products.filter(category__cid__in=categories).distinct()
    if len(vendors) > 0:
        products = products.filter(vendor__vid__in=vendors).distinct()

    data = render_to_string("core/async/product-list.html", {
        "products": products,
    })
    return JsonResponse({"data": data, "product_count": len(products)})

def add_to_cart(request):
    cart_product = {}
    title = request.GET["title"]
    pid = request.GET["pid"]
    quantity = int(request.GET["quantity"])
    price = float(request.GET["price"])
    image = request.GET["image"]

    cart_product[pid] = {
        'title': title,
        'quantity': quantity,
        'price': price,
        'image': image,
        'pid': pid,
    }
    
    if "cart_data_object" in request.session:
        cart_data = request.session["cart_data_object"]
        cart_data[pid] = cart_product[pid]
        # Save the cart data back to the session
        request.session["cart_data_object"] = cart_data
    else:
        request.session["cart_data_object"] = cart_product
    return JsonResponse({"data": request.session["cart_data_object"], "total_cart_items": len(request.session["cart_data_object"])})


def cart_view(request):
    cart_total_amount = 0
    product_amount = 0
    cart_data = ""
    if "cart_data_object" in request.session:
        for pid, item in request.session["cart_data_object"].items():
            cart_total_amount += item['quantity'] * item['price']
        product_amount = len(request.session["cart_data_object"])
        cart_data = reversed(request.session["cart_data_object"].values())
    context = {
            'cart_total_amount': cart_total_amount,
            'cart_data': cart_data,
            'product_amount': product_amount,
    }
    return render(request, "core/cart.html", context)

def remove_from_cart(request):
    pid = request.GET["pid"]
    cart_data = request.session["cart_data_object"]
    if pid in cart_data:
        del cart_data[pid]
        product_amount = len(cart_data)
        cart_total_amount = 0
        for product in cart_data.values():
            cart_total_amount += product['price'] * product['quantity']
        request.session["cart_data_object"] = cart_data
        # Explicitly mark the session as modified
        request.session.modified = True
        data = {
            "product_amount": product_amount,
            "cart_total_amount": cart_total_amount,
        }
        return JsonResponse({"data": data})
    return JsonResponse({"data": cart_data, "message": "Product PID not found in cart."}, status=404)

def update_cart(request):
    pid = request.GET["pid"]
    quantity = request.GET["quantity"]
    cart_data = request.session["cart_data_object"]
    product_subtotal = cart_data[pid]["quantity"] * cart_data[pid]["price"]
    cart_total_amount = 0
    if pid in cart_data:
        cart_data[pid]["quantity"] = int(quantity)
        product_subtotal = int(quantity) * cart_data[pid]["price"]    
    for product in cart_data.values():
        cart_total_amount += product['quantity'] * product['price']
    request.session["cart_data_object"] = cart_data
    request.session.modified = True
    return JsonResponse({"data": {"product_subtotal": product_subtotal, "cart_total_amount": cart_total_amount}})

def save_checkout_info(request):
    cart_total_amount = 0   

    if request.method == "POST":
        full_name = request.POST["full_name"]
        email = request.POST["email"]
        mobile = request.POST["mobile"]
        address = request.POST["address"]
        city = request.POST["city"]
        state  = request.POST["state"]
        country = request.POST["country"]
        # request.session["mobile"] = mobile
        # request.session["email"] = email
        request.session["address"] = address
        # request.session["full_name"] = full_name
        request.session["city"] = city
        request.session["state"] = state
        request.session["country"] = country
        if "cart_data_object" in request.session and len(request.session["cart_data_object"]) > 0:
            cart_data = request.session["cart_data_object"]
            # Get the cart total amount
            for product in cart_data.values():
                cart_total_amount += product["quantity"] * product["price"]
            # Create new order
            order = CartOrder.objects.create(
                user=request.user,
                price=cart_total_amount,
                full_name=full_name,
                email=email,
                address=address,
                city=city,
                state=state,
                phone=mobile,
                country=country,
            )

templates/core/cart.html
{% extends 'partials/base.html' %}
{% load static %}
{% load custom_tags%}
{% block content %}
    <!--End header-->
    <main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop
                    <span></span> Cart
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Your Cart</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">There are <span class="text-brand" id="product-amount">{{product_amount}}</span> products in your cart</h6>
                        <h6 class="text-body"><a href="#" class="text-muted"><i class="fi-rs-trash mr-5"></i>Clear Cart</a></h6>
                    </div>
                </div>
            </div>
            <form action="{% url 'core:save-checkout-info' %}" method="POST">
            {% csrf_token %}
            <div class="row">
                
                <div class="col-lg-8">
                    {% if product_amount %}
                    <div class="table-responsive shopping-summery" id="cart-table">
    
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th class="custome-checkbox start pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="">
                                        <label class="form-check-label" for="exampleCheckbox11"></label>
                                    </th>
                                    <th scope="col">Product</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Unit Price</th>
                                    <th scope="col" class="text-center">Quantity</th>
                                    <th scope="col">Subtotal</th>
                                    <th scope="col">Refresh</th>
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product in cart_data %}
                                <tr class="pt-30" id="product-{{product.pid}}">
                                    <td class="custome-checkbox pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="">
                                        <label class="form-check-label" for="exampleCheckbox1"></label>
                                    </td>
                                    <td class="image product-thumbnail pt-40"><img src="{{product.image}}" alt="#"></td>
                                    <td class="product-des product-name">
                                        <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url 'core:product-detail' product.pid %}">{{product.title}}</a></h6>
                                        <div class="product-rate-cover">
                                            <div class="product-rate d-inline-block">
                                                <div class="product-rating" style="width:90%">
                                                </div>
                                            </div>
                                            <span class="font-small ml-5 text-muted"> (4.0)</span>
                                        </div>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 class="text-body">${{product.price|floatformat:2}} </h4>
                                    </td>
                                    <td class="text-center detail-info" data-title="Stock">
                                        <div class="detail-extralink mr-15">
                                            <input type="number" class="w-25" min="1" value={{product.quantity}} step="1" id="product-quantity-{{product.pid}}" >
                                        </div>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 class="text-brand" id="product-subtotal-{{product.pid}}">${%multiply product.price product.quantity as result%}{{result|floatformat:2}}</h4>
                                    </td>
                                    <td class="action text-center" data-title="Refresh"><button type="button" style="border: none; background: none;" class="text-body refresh-product" data-product={{product.pid}}><i class="fi-rs-refresh"></i></button></td>
                                    <td class="action text-center" data-title="Remove"><button type="button" style="border: none; background: none;" class="text-body delete-product" data-product={{product.pid}}><i class="fi-rs-trash"></i></button></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% endif %}
                    <div class="row mt-4">
                        <h4 class="mb-30">Bio Data</h4>
                        <div class="row">
                            <div class="form-group col-lg-12">
                                <label for="">Full Name</label>
                                <input type="text" required="" name="full_name" value="{{request.user.username|title}}" placeholder="Full Name *">
                            </div>
                            <div class="form-group col-lg-6">
                                <label for="">Email</label>
                                <input type="text" required="" name="email"  placeholder="Email *" value="{{request.user.email}}">
                            </div>
                            <div class="form-group col-lg-6">
                                <label for="">Mobile</label>
                                <input type="text" name="mobile" value="{{request.user.profile.phone}}" required="" placeholder="Mobile *">
                            </div>
                        </div>
                        <h4 class="mb-30">Shipping Details</h4>
                        <div class="row">
                            <div class="form-group col-lg-6">
                                <label for="">Address</label>
                                <input type="text" name="address" value="{{request.session.address}}" placeholder="Address *">
                            </div>
                            <div class="form-group col-lg-6">
                                <label for="">City</label>
                                <input type="text" name="city"  placeholder="City *" value="{{request.session.city}}">
                            </div>
                            <div class="form-group col-lg-6">
                                <label for="">State</label>
                                <input type="text" name="state" value="{{request.session.state}}" placeholder="State *">
                            </div>
                            <div class="form-group col-lg-6">
                                <label for="">Country</label>
                                <input type="text" name="country" value="{{request.session.country}}" placeholder="Country *">
                            </div>
                        </div>
                    </div>
                </div>
                {% if product_amount %}
                <div class="col-lg-4" id="cart-bill">
                    <div class="border p-md-4 cart-totals ml-30">
                        <div class="table-responsive">
                            <table class="table no-border">
                                <tbody>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted" >Subtotal</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-brand text-end" id="cart-subtotal-amount">${{cart_total_amount|floatformat:2}}</h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Shipping</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h5 class="text-heading text-end">Free</h5> </tr> <tr>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Total</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-brand text-end" id="cart-total-amount">${{cart_total_amount|floatformat:2}}</h4>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <button type="submit" class="btn mb-20 w-100">Proceed To Checkout<i class="fi-rs-sign-out-ml-15"></i></button>
                    </div>
                </div>
                {% endif %}
            
            </div>
            </form>
        </div>
    </main>
{% endblock %}

templates/core/checkout.html
{% extends 'partials/base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
    
    <main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop <span></span> Checkout
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Checkout</h1>
                    <div class="d-flex justify-content-between"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-7">
                    <div class="row">
                        {% for item in order_items %}
                        <div class="col-lg-6 mb-2">
                            <div class="card" style="max-width: 540px;">
                                <div class="row g-0">
                                    <div class="col-sm-4">
                                        <img src="{{item.image}}" style="width: 100%; height: 100%; object-fit: cover;" class="rounded-start" alt="Card image" />
                                    </div>
                                    <div class="col-sm-8">
                                        <div class="card-body">
                                            <h5 class="card-title">{{item.item}}</h5>
                                            <p class="card-text fs-sm">Quantity: {{ item.quantity }}</p>
                                            <p class="card-text fs-sm">Price: ${{ item.price|floatformat:2 }}</p>
                                            <p class="card-text fs-sm">Total: ${% multiply item.quantity item.price as subtotal %}{{subtotal|floatformat:2}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="border cart-totals mb-50">
                        <div class="d-flex align-items-end justify-content-between mb-30">
                            <h4>Order Summary</h4>
                        </div>

                        <div>
                            <div class="d-flex justify-content-between mb-2">
                                <p class="fw-bold">Tax</p>
                                <p>$0</p>
                            </div>
                            <div class="d-flex justify-content-between mb-2">
                                <p class="fw-bold">Shipping</p>
                                <p>$0</p>
                            </div>
                            <div class="d-flex justify-content-between mb-2">
                                <p class="fw-bold">Discount</p>
                                <p>${{ order.saved }}</p>
                            </div>
                            <div class="d-flex justify-content-between mb-2">
                                <p class="fw-bold">Total</p>
                                <p>${{order.price}}</p>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-50">
                        <div class="col-lg-12">
                            <form method="POST" class="apply-coupon" action="{% url 'core:checkout' order.oid %}">
                                {% csrf_token %}
                                <input type="text" name="code" placeholder="Enter Coupon Code..." />
                                <button class="btn btn-md" type="submit" name="apply-coupon">Apply</button>
                            </form>
                        </div>
                    </div>

                    <button type="button" class="btn w-100" id="checkout-button" style="background-color: blueviolet;">Pay With Stripe (Credit or Debit Card)</button>
                    <div id="paypal-button-container" class="mt-3"></div>
                </div>
            </div>
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>
    <script src="https://js.stripe.com/v3/"></script>

    <script>
        paypal.Buttons({
            createOrder: function(data, action) {
                return action.order.create({
                    purchase_units: [
                        {
                            amount: {
                                value: "{{order.price}}"
                            }
                        }
                    ]
                })
            },
            onApprove: function(data, action) {
                return action.order.capture().then(function(Detail) {
                    console.log(Detail);
                    if (Detail.status  === 'COMPLETED') {
                        window.location.href = `/payment-completed/{{order.oid}}?status=${Detail.status}`;
                    }
                });
            }, 
        }).render("#paypal-button-container");
    </script>

    <script>
        var stripe = Stripe("{{stripe_publishable_key}}");
        var checkoutButton = document.getElementById("checkout-button");

        try {
            checkoutButton.addEventListener("click", function () {
            var email = "{{booking.email}}";

            checkoutButton.innerHTML = "Processing <i class='fas fa-spinner fa-spin'></i>";

            fetch("/api/create_checkout_session/{{order.oid}}/", {
                method: "POST",
                body: JSON.stringify({ email: email }),
            })
                .then(function (response) {
                    console.log(response);
                    console.log(stripe);
                    return response.json();
                })
                .then(function (session) {
                    return stripe.redirectToCheckout({ sessionId: session.sessionId });
                })
                .then(function (result) {
                    if (result.error) {
                        alert(result.error.message);
                    }
                })
                .catch(function (error) {
                    console.log("Error: ", error);
                });
        });
    
    
        } catch (error) {
            console.log(error);
        }
    </script>
    <script>
        let stripe = Stripe("{{stripe_publishable_key}}")
        let checkoutButton = $("#checkout-button")

        try {
            checkoutButton.on("click", function() {
                let email = "{{order.email}}"

                checkoutButton.html("Processing...")

                fetch("/api/create_checkout_session/{{order.oid}}/", {
                    {% comment %} headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}'  // Include the CSRF token
                    }, {% endcomment %}
                    method: 'POST',
                    body: JSON.stringify({
                        email: email
                    })
                }).then(function(response) {
                    console.log(response);
                })
            })
        } catch (error) {
            console.log(error)
        }
    </script>


{% endblock content %}
    